<?php

declare(strict_types=1);

namespace App\Service\Permission;

use App\Exception\BusinessException;
use App\Http\Common\ResultCode;
use App\Library\DataPermission\Attribute\DataScope;
use App\Library\DataPermission\ScopeType;
use App\Model\Enums\User\Status;
use App\Model\Permission\Role;
use App\Model\Permission\User;
use App\Model\TenantProject;
use App\Repository\Permission\RoleRepository;
use App\Repository\Permission\UserRepository;
use App\Service\IService;
use Hyperf\Collection\Collection;
use Hyperf\DbConnection\Db;

/**
 * @extends IService<User>
 */
final class UserService extends IService
{
    public function __construct(
        protected readonly UserRepository $repository,
        protected readonly RoleRepository $roleRepository
    ) {}

    public function getInfo(int $id): ?User
    {
        return $this->repository->findById((string) $id);
    }

    public function resetPassword(?int $id): bool
    {
        if ($id === null) {
            return false;
        }
        $entity = $this->repository->findById($id);
        $entity->resetPassword();
        $entity->save();
        return true;
    }

    public function getUserRole(int $id): Collection
    {
        return $this->repository->findById($id)->roles()->get();
    }

    public function batchGrantRoleForUser(int $id, array $roleCodes): void
    {
        $this->repository->findById($id)
            ->roles()
            ->sync(
                $this->roleRepository->list([
                    'code' => $roleCodes,
                ])->map(static function (Role $role) {
                    return $role->id;
                })
            );
    }

    public function create(array $data): mixed
    {
        return Db::transaction(function () use ($data) {
            /** @var User $entity */
            $entity = parent::create($data);
            $this->handleWith($entity, $data);
            return $entity;
        });
    }

    public function updateById(mixed $id, array $data): mixed
    {
        return Db::transaction(function () use ($id, $data) {
            /** @var null|User $entity */
            $entity = $this->repository->findById($id);
            if (empty($entity)) {
                throw new BusinessException(ResultCode::NOT_FOUND);
            }
            $entity->fill($data)->save();
            $this->handleWith($entity, $data);
        });
    }

    public function switchProject(User $user, ?int $projectId): void
    {
        if (! $user->isTenantUser()) {
            throw new BusinessException(ResultCode::FORBIDDEN);
        }

        $projectId = $projectId !== null ? (int) $projectId : null;
        if ($projectId !== null && ! $this->projectAccessible($user, $projectId)) {
            throw new BusinessException(ResultCode::UNPROCESSABLE_ENTITY, '当前项目不存在、已停用或无权访问');
        }

        $user->last_project_id = $projectId;
        $user->save();
    }

    public function syncLastProjectId(User $user, ?int $excludeProjectId = null): void
    {
        if (! $user->isTenantUser()) {
            return;
        }

        $currentProjectId = $user->last_project_id ? (int) $user->last_project_id : null;
        if ($currentProjectId !== null && $this->projectAccessible($user, $currentProjectId, $excludeProjectId)) {
            return;
        }

        $user->last_project_id = $this->resolveAccessibleProjectId($user, $excludeProjectId);
        $user->save();
    }

    #[DataScope(
        scopeType: ScopeType::CREATED_BY,
        onlyTables: ['user'],
        createdByColumn: 'id'
    )]
    public function page(array $params, int $page = 1, int $pageSize = 10): array
    {
        return parent::page($params, $page, $pageSize); // TODO: Change the autogenerated stub
    }

    protected function handleWith(User $entity, array $data): void
    {
        if (isset($data['department'])) {
            $entity->department()->sync($data['department']);
        }
        if (isset($data['position'])) {
            $entity->position()->sync($data['position']);
        }
        if (isset($data['policy'])) {
            $policy = $entity->policy()->first();
            if ($policy) {
                if (isset($data['policy']['id'])) {
                    $policy->fill($data['policy'])->save();
                } else {
                    $entity->policy()->delete();
                }
            } else {
                if (! empty($data['policy'])) {
                    $entity->policy()->create($data['policy']);
                }
            }
        }
    }

    private function projectAccessible(User $user, int $projectId, ?int $excludeProjectId = null): bool
    {
        if ($excludeProjectId !== null && $projectId === $excludeProjectId) {
            return false;
        }

        $query = TenantProject::query()
            ->whereKey($projectId)
            ->where('tenant_id', $user->tenant_id)
            ->where('status', Status::Normal->value);

        if (! $user->isTenantAdmin()) {
            $query->whereHas('members', static function ($query) use ($user) {
                $query->whereKey($user->id);
            });
        }

        return $query->exists();
    }

    private function resolveAccessibleProjectId(User $user, ?int $excludeProjectId = null): ?int
    {
        $query = TenantProject::query()
            ->where('tenant_id', $user->tenant_id)
            ->where('status', Status::Normal->value)
            ->orderByDesc('is_default')
            ->orderByDesc('id');

        if ($excludeProjectId !== null) {
            $query->where('id', '!=', $excludeProjectId);
        }

        if (! $user->isTenantAdmin()) {
            $query->whereHas('members', static function ($query) use ($user) {
                $query->whereKey($user->id);
            });
        }

        $projectId = $query->value('id');
        return $projectId !== null ? (int) $projectId : null;
    }
}
