name: Frontend Tests
on:
  push:
  pull_request:
  workflow_call:
jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Test
        run: echo "Running E2E tests on ${{ matrix.os }}"